# .github/FUNDING.yml
github: [genyleap]
custom:
  - "ETH/GENY (ERC20): https://etherscan.io/address/0x6E99f7564d060AA141dcC47ede34379Bad0cDCCC"
  - "BTC: https://blockchair.com/bitcoin/address/BC1Q2Q7G83V9UXATK0YSPFVCU3YDNMESEU3Y7P9J9N"