#!/usr/bin/env python3
"""Generate bundled, offline translations of the GPL text used by the UI."""

from __future__ import annotations

import concurrent.futures
import json
import re
import urllib.parse
from pathlib import Path

from generate_ui_translations import LOCALES, request_translation


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "LICENSE"
OUTPUT_ROOT = ROOT / "ui" / "Translations" / "licenses"
BUNDLE = ROOT / "ui" / "Translations" / "licenses.js"


def translation_units(text: str) -> list[str]:
    units: list[str] = []
    for paragraph in re.split(r"\n\s*\n", text.strip()):
        paragraph = paragraph.strip()
        if not paragraph:
            continue
        while len(urllib.parse.quote(paragraph)) > 2300:
            limit = min(900, len(paragraph))
            candidates = [
                paragraph.rfind("\n", 0, limit),
                paragraph.rfind(". ", 0, limit),
                paragraph.rfind("; ", 0, limit),
                paragraph.rfind(" ", 0, limit),
            ]
            split_at = max(candidates)
            if split_at < 120:
                split_at = limit
            elif paragraph[split_at:split_at + 2] in {". ", "; "}:
                split_at += 1
            units.append(paragraph[:split_at].strip())
            paragraph = paragraph[split_at:].strip()
        if paragraph:
            units.append(paragraph)
    return units


def translate_units(units: list[str], target: str) -> str:
    translated: list[str] = []
    batch: list[str] = []
    batch_size = 0

    def flush() -> None:
        nonlocal batch, batch_size
        if not batch:
            return
        translated.extend(request_translation(batch, target))
        batch = []
        batch_size = 0

    for unit in units:
        estimated = len(urllib.parse.quote(unit))
        if batch and (len(batch) >= 10 or batch_size + estimated > 2600):
            flush()
        batch.append(unit)
        batch_size += estimated
    flush()
    return "\n\n".join(translated).strip() + "\n"


def main() -> int:
    source_text = SOURCE.read_text(encoding="utf-8")
    units = translation_units(source_text)
    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)

    def generate(locale: str, target: str) -> tuple[str, str]:
        output = OUTPUT_ROOT / f"{locale}.txt"
        if output.exists() and output.stat().st_size > 10_000:
            return locale, output.read_text(encoding="utf-8")
        print(f"{locale}: translating {len(units)} license blocks...", flush=True)
        translated = translate_units(units, target)
        output.write_text(translated, encoding="utf-8")
        return locale, translated

    translations: dict[str, str] = {}
    with concurrent.futures.ThreadPoolExecutor(max_workers=4) as executor:
        futures = [executor.submit(generate, locale, target) for locale, target in LOCALES.items()]
        for future in concurrent.futures.as_completed(futures):
            locale, translated = future.result()
            translations[locale] = translated

    ordered = {locale: translations[locale] for locale in LOCALES}
    BUNDLE.write_text(
        ".pragma library\n\n"
        "// Generated by scripts/generate_license_translations.py. Do not edit manually.\n"
        "var licenses = " + json.dumps(ordered, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
